repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

environments:
  aws:
    values:
      - dnsSuffix: {{ env "DNS_SUFFIX" | default "" }}
  azure:
    values:
      - dnsSuffix: {{ env "DNS_SUFFIX" | default "" }}

releases:
  - name: metallb
    namespace: kube-system
    version: 0.1.21
    chart: bitnami/metallb
    wait: true
    values:
      - configInline:
          address-pools:
            - name: generic-cluster-pool
              protocol: layer2
              addresses:
              - {{ requiredEnv "IP_ADDR" }}
