# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: movie_db
#   namespace: default
# data:
#   POSTGRES_USER: 'movie_user'
#   POSTGRES_PASSWORD: 'movie_password'
#   POSTGRES_DB: 'movie_db_dev'

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: movie_db
#   namespace: default
# type: Opaque
# data:
#   POSTGRES_PASSWORD: bW92aWVfcGFzc3dvcmQK
#   POSTGRES_USER: movie_user
#   POSTGRES_DB: movie_db_dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie-service
  name: movie-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: singhujjwal/movie-service:0.1
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        workingDir: /app/
        env:
          - name: DATABASE_URI
            value: postgresql://movie_user:movie_password@postgresql/movie_db_dev
          - name: CAST_SERVICE_HOST_URL
            value: http://cast-service:8000/api/v1/casts/
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/movies/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: ClusterIP
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-ing
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: redis.civo.singhjee.in
    http:
      paths:
      - path: /api/v1/movies/
        pathType: Prefix
        backend:
          service:
            name: movie-service
            port:
              number: 8000