# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: movie_db
#   namespace: default
# data:
#   POSTGRES_USER: 'movie_user'
#   POSTGRES_PASSWORD: 'movie_password'
#   POSTGRES_DB: 'movie_db_dev'

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: movie_db
#   namespace: default
# type: Opaque
# data:
#   POSTGRES_PASSWORD: bW92aWVfcGFzc3dvcmQK
#   POSTGRES_USER: movie_user
#   POSTGRES_DB: movie_db_dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cast-service
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: singhujjwal/cast-service:0.1
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        workingDir: /app/
        env:
          - name: DATABASE_URI
            value: postgresql://movie_user:movie_password@postgresql/cast_db_dev
        ports:
        - containerPort: 8000
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  type: ClusterIP
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cast-ing
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: redis.civo.singhjee.in
    http:
      paths:
      - path: /api/v1/casts/
        pathType: Prefix
        backend:
          service:
            name: cast-service
            port:
              number: 8000

